#!/usr/bin/env sh

sudo pacman -Syu --noconfirm --needed base base-devel curl stow

stow/setup

./yay

yay -S --noconfirm --needed git neovim fish sway bemenu-wlroots i3blocks \
  i3blocks-contrib rustup ruby crystal

rustup default stable
rustup component add rust-src # needed for autocompletion

# install vim-plug
curl --create-dirs -fLo $HOME/.local/share/nvim/site/autoload/plug.vim \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
